### PR TITLE
Update download.md for 0.6.1 release

### PR DESCRIPTION
**Pull request by zhongqishang**
Update download.md for 0.6.1 realse

### CODE REVIEW

**Comment by justinmclean** [comment]
I've not looked at this page in detail, but since Amoro doesn't have any ASF releases yet, it needs to be made clear that these are not ASF releases.

**Comment by zhongqishang** [comment]
> I've not looked at this page in detail, but since Amoro doesn't have any ASF releases yet, it needs to be made clear that these are not ASF releases.

@justinmclean Thanks for your reminder, I have clarified the non-Apache release version.

**Comment by zhoujinsong** [comment]
@zhongqishang  There is some conflict you may want to fix.

**Review by zhoujinsong — APPROVED** [review]
LGTM. Thanks a lot for your contribution!

**Comment by justinmclean** [comment]
I think a little more needs to be done here as it needs to be 100% clear to any user that there are not official ASF releases

**Comment by zhoujinsong** [comment]
Maybe we should group all the history releases under the title: Non-ASF official release.
HDYT? @justinmclean @zhongqishang

**Comment by zhongqishang** [comment]
> Maybe we should group all the history releases under the title: Non-ASF official release. HDYT? @justinmclean @zhongqishang

They are now marked as a not official ASF releases. 100% clear to any user is hard beacuse they download from a apache site, maybe remove all the non-asf release in website and only have a link to github releases? 

Refer to: https://seatunnel.apache.org/download/

**Comment by justinmclean** [comment]
Seatunnel has non-ASF releases on a separate page. Again I think we need to be clearer here.

**Comment by justinmclean** [comment]
Also, the English needs to be improved, for instance, "Historical versions of non-Apache" doesn't make a lot of sense to a native English speaker. I can help out here if you want.

**Comment by zhongqishang** [comment]
@justinmclean If you can provide help, I would be very grateful.

**Pull request merged**
